### ISSUE TITLE
TimeStamp Problem with Tableau Connector

### ISSUE THREAD

**Issue by nicopoal** [tableau-mkt/insights-data-connector#1]
Hi,

When connecting connector on newrelic account with tableau, timestamps seems to be not recognize and appears as "null" in tableau :-( i tried different format type in tableau but no change :-(
<img width="148" alt="capture d ecran 2017-06-08 a 12 31 41" src="https://user-images.githubusercontent.com/29275908/26924756-64c05ea0-4c47-11e7-8267-1fda2ad8174a.png">
<img width="155" alt="capture d ecran 2017-06-08 a 12 31 29" src="https://user-images.githubusercontent.com/29275908/26924757-64c7c6d6-4c47-11e7-9ba7-3c0dd2a1bdf3.png">

**Comment by iamEAP** [comment]
Thanks for the report, @nicopoal. Did a quick test on with 10.2.2 and didn't experience the same. What version of Tableau are you using?

**Comment by nicopoal** [comment]
Hi, thanks you for your quick reply. i use Tableau 10.3

**Comment by iamEAP** [comment]
Thanks @nicopoal.  I'm also unable to reproduce in 10.3.  I also tried switching product language to French (in the event the WDC connection pane has different locale settings for dates for some reason).

Is the property you're trying to use in your NRQL query a custom key, or is it a core property of an Event type in Insights?  In your screenshot above, it appears as though the property you're referencing may be `request.headers.me..`...something.

For reference, the NRQL query I'm using to test is:

```sql
SELECT timestamp, appName FROM Transaction
```

**Comment by nicopoal** [comment]
I tried with the same NRQL query than you and I always get "null", I really do not understand :-( 
I'll check with the sysadmins which version of new relic's agents is setup on servers.

Thank you very much for your help :-)

**Comment by iamEAP** [comment]
@nicopoal Perhaps you could also provide a sample JSON response for the query above from New Relic?  It's a display type on queries you run on the platform.  Wondering if they store timestamps differently across accounts.

**Comment by iamEAP** [comment]
Cleaning out the backlog...  Feel free to re-open if you have further details or questions.
